Importing Libraries and Datasets

In [13]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.multioutput import MultiOutputRegressor
from sklearn.metrics import mean_squared_error

In [14]:
dataset = pd.read_csv("result.csv")

Reshaping Datasets to fit for model

In [16]:
dataset.head()
dataset.dtypes
ds  = dataset.drop(columns = 'prediction')

In [17]:
X = ds.iloc[::].values
ReshapedX = np.reshape(X, (3672, 128))

In [18]:
print(X[:,[0,1,2,3]])
print(ReshapedX[:, [0, 1, 2, 3, 4, 5, 6, 7, 127]])

[[9.2833e+04 7.0520e+01 1.6000e-02 0.0000e+00]
 [0.0000e+00 7.0700e+01 1.6000e-02 1.0000e+00]
 [0.0000e+00 7.0700e+01 1.6000e-02 2.0000e+00]
 ...
 [0.0000e+00 1.0868e+02 1.6000e-02 2.9000e+01]
 [0.0000e+00 1.0708e+02 1.6000e-02 3.0000e+01]
 [0.0000e+00 1.0532e+02 1.6000e-02 3.1000e+01]]
[[9.28330e+04 7.05200e+01 1.60000e-02 ... 1.60000e-02 1.00000e+00
  3.10000e+01]
 [9.40290e+04 7.12200e+01 2.28600e+00 ... 1.60000e-02 1.00000e+00
  3.10000e+01]
 [9.55500e+04 7.18200e+01 2.31500e+00 ... 1.60000e-02 1.00000e+00
  3.10000e+01]
 ...
 [1.15338e+05 1.13150e+02 2.83400e+00 ... 2.53100e+00 1.00000e+00
  3.10000e+01]
 [1.00466e+05 1.12660e+02 2.47200e+00 ... 2.80600e+00 1.00000e+00
  3.10000e+01]
 [1.08006e+05 1.12170e+02 2.65400e+00 ... 2.74500e+00 1.00000e+00
  3.10000e+01]]


In [19]:
data = pd.read_csv("result.csv")
data.head()

accesses   temp  power  number  prediction
0     92833  70.52  0.016       0       71.22
1         0  70.70  0.016       1       71.40
2         0  70.70  0.016       2       71.40
3         0  70.52  0.016       3       71.22
4         0  70.69  0.016       4       71.37

In [20]:
Y = data.iloc[:,-1].values
ReshapedY = np.reshape(Y, (3672, 32))
print(Y)
print(ReshapedY[:, [0, 1, 2,3, 4,31]])

[ 71.22  71.4   71.4  ... 108.31 106.72 104.95]
[[ 71.22  71.4   71.4   71.22  71.37  70.73]
 [ 71.82  71.99  72.    71.83  71.95  70.86]
 [ 72.33  72.51  72.52  72.35  72.46  70.96]
 ...
 [112.66 114.71 116.54 117.6  117.56 105.7 ]
 [112.17 114.2  116.03 117.08 117.04 105.32]
 [111.63 113.65 115.48 116.53 116.48 104.95]]


Splitting into Training sets and Testing sets

In [21]:

X_train, X_test, y_train, y_test = train_test_split(ReshapedX, ReshapedY, test_size = 0.2, random_state = 0)

Implementing Model

In [22]:

regressor = GradientBoostingRegressor()
# Wrap the GBM model with MultiOutputRegressor
model = MultiOutputRegressor(regressor)
model.fit(X_train, y_train)

MultiOutputRegressor(estimator=GradientBoostingRegressor())

Running on test sets

In [23]:
y_pred = model.predict(ReshapedX)
print(y_pred)

[[ 71.19231784  71.36720938  71.4065789  ...  70.94469949  70.93437186
   70.76533992]
 [ 71.78412056  71.98377744  71.99876926 ...  71.06550507  71.0521855
   70.87435164]
 [ 72.43834785  72.63449417  72.6004093  ...  71.16292169  71.14503387
   70.97199519]
 ...
 [112.72175029 114.55234362 116.45984114 ... 109.10244606 107.51501586
  105.82507231]
 [112.68374244 114.18987253 116.08858306 ... 108.89179611 107.20235274
  105.43187983]
 [112.04969664 113.45500866 115.43975802 ... 108.38020244 106.65796215
  105.18594292]]


In [24]:

mse = mean_squared_error(ReshapedY, y_pred)
print(mse)


0.06576620598388697


In [25]:
# Assuming 'y_true' is the true values and 'y_pred' is the predicted values
# mse = mean_squared_error(y_true, y_pred)
mean_actual = np.mean(ReshapedY)
nmse = (mse / mean_actual) * 100

print("Normalized Mean Squared Error (NMSE):", nmse)


Normalized Mean Squared Error (NMSE): 0.07770122973244253
