Importing Libraries and Datasets

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
# from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [1]:
!pip install xgboost


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 18.8 MB/s eta 0:00:00a 0:00:01

[notice] A new release of pip is available: 23.1.1 -> 23.1.2
[notice] To update, run: python3.11 -m pip install --upgrade pip


In [3]:
import xgboost as xgb

In [4]:
dataset = pd.read_csv("result.csv")

Reshaping Datasets to fit for model

In [5]:
dataset.head()
dataset.dtypes
ds  = dataset.drop(columns = 'prediction')

In [6]:
X = ds.iloc[::].values
ReshapedX = np.reshape(X, (3672, 128))

In [7]:
print(X[:,[0,1,2,3]])
print(ReshapedX[:, [0, 1, 2, 3, 4, 5, 6, 7, 127]])

[[9.2833e+04 7.0520e+01 1.6000e-02 0.0000e+00]
 [0.0000e+00 7.0700e+01 1.6000e-02 1.0000e+00]
 [0.0000e+00 7.0700e+01 1.6000e-02 2.0000e+00]
 ...
 [0.0000e+00 1.0868e+02 1.6000e-02 2.9000e+01]
 [0.0000e+00 1.0708e+02 1.6000e-02 3.0000e+01]
 [0.0000e+00 1.0532e+02 1.6000e-02 3.1000e+01]]
[[9.28330e+04 7.05200e+01 1.60000e-02 ... 1.60000e-02 1.00000e+00
  3.10000e+01]
 [9.40290e+04 7.12200e+01 2.28600e+00 ... 1.60000e-02 1.00000e+00
  3.10000e+01]
 [9.55500e+04 7.18200e+01 2.31500e+00 ... 1.60000e-02 1.00000e+00
  3.10000e+01]
 ...
 [1.15338e+05 1.13150e+02 2.83400e+00 ... 2.53100e+00 1.00000e+00
  3.10000e+01]
 [1.00466e+05 1.12660e+02 2.47200e+00 ... 2.80600e+00 1.00000e+00
  3.10000e+01]
 [1.08006e+05 1.12170e+02 2.65400e+00 ... 2.74500e+00 1.00000e+00
  3.10000e+01]]


In [8]:
data = pd.read_csv("result.csv")
data.head()

accesses   temp  power  number  prediction
0     92833  70.52  0.016       0       71.22
1         0  70.70  0.016       1       71.40
2         0  70.70  0.016       2       71.40
3         0  70.52  0.016       3       71.22
4         0  70.69  0.016       4       71.37

In [9]:
Y = data.iloc[:,-1].values
ReshapedY = np.reshape(Y, (3672, 32))
print(Y)
print(ReshapedY[:, [0, 1, 2,3, 4,31]])

[ 71.22  71.4   71.4  ... 108.31 106.72 104.95]
[[ 71.22  71.4   71.4   71.22  71.37  70.73]
 [ 71.82  71.99  72.    71.83  71.95  70.86]
 [ 72.33  72.51  72.52  72.35  72.46  70.96]
 ...
 [112.66 114.71 116.54 117.6  117.56 105.7 ]
 [112.17 114.2  116.03 117.08 117.04 105.32]
 [111.63 113.65 115.48 116.53 116.48 104.95]]


Splitting into Training sets and Testing sets

In [10]:

X_train, X_test, y_train, y_test = train_test_split(ReshapedX, ReshapedY, test_size = 0.2, random_state = 0)

Implementing Model

In [12]:

regressor = xgb.XGBRegressor()
regressor.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             n_estimators=100, n_jobs=None, num_parallel_tree=None,
             predictor=None, random_state=None, ...)

Running on test sets

In [13]:
y_pred = regressor.predict(ReshapedX)
print(y_pred)

[[ 71.23984   71.419754  71.41971  ...  70.91398   70.900406  70.73386 ]
 [ 71.79659   71.99177   71.980576 ...  71.05045   71.03918   70.86446 ]
 [ 72.36486   72.52827   72.538635 ...  71.14159   71.122215  70.96381 ]
 ...
 [112.71181  114.89887  116.58203  ... 109.15535  107.455666 105.74301 ]
 [112.261284 114.23365  115.97547  ... 108.72643  107.103134 105.299644]
 [111.62479  113.58245  115.45597  ... 108.2375   106.7108   105.004845]]


In [14]:

mse = mean_squared_error(ReshapedY, y_pred)
print(mse)


0.04937732543930069


In [15]:
# Assuming 'y_true' is the true values and 'y_pred' is the predicted values
# mse = mean_squared_error(y_true, y_pred)
mean_actual = np.mean(ReshapedY)
nmse = (mse / mean_actual) * 100

print("Normalized Mean Squared Error (NMSE):", nmse)


Normalized Mean Squared Error (NMSE): 0.05833815179292366
